version: 2.1
description: Commands for integrating Snyk into your CircleCI builds
commands:
  install_snyk:
    description: "Install the latest version of the Snyk CLI"
    parameters:
      suggestions:
        type: boolean
        description: Whether or not to show suggestions
        default: false
    steps:
      - run:
          name: Install Snyk
          command: |
            if [[ ! -x "/usr/local/bin/snyk" ]]; then
              curl -s https://api.github.com/repos/snyk/snyk/releases/latest | grep "browser_download_url" | grep linux | cut -d '"' -f 4 | wget -qi -
              sha256sum -c snyk-linux.sha256
              sudo mv snyk-linux /usr/local/bin/snyk
              sudo chmod +x /usr/local/bin/snyk
            fi
      - when:
          condition: << parameters.suggestions >>
          steps:
            - run:
                name: Disable Snyk suggestions
                command: snyk config set disableSuggestions=true
  check_code_with_snyk:
    description: "Check your application dependencies for known vulnerabilities with Snyk"
    parameters:
      project:
        type: string
        description: Override the default project name
        default: ""
      args:
        type: string
        description: Pass arbitrary arguments to the Snyk CLI
        default: ""
      type:
        type: enum
        description: Whether to run track results on Snyk and recieve alerts for new vulnerabilities
        default: "monitor"
        enum: ["monitor", "test"]
    steps:
      - run:
          name: Run Snyk to check dependencies
          command: snyk << parameters.type >> --project-name=<< parameters.project >> << parameters.args >>
  check_docker_with_snyk:
    description: "Check your Docker images for known vulnerabilities with Snyk"
    parameters:
      image:
        type: string
        description: The image repository to check
      dockerfile:
        type: string
        description: The path to the local Dockerfile
        default: Dockerfile
      tag:
        type: string
        description: The image tag to check
        default: latest
      project:
        type: string
        description: Override the default project name
        default: ""
      args:
        type: string
        description: Pass arbitrary arguments to the Snyk CLI
        default: ""
      type:
        type: enum
        description: Whether to run track results on Snyk and recieve alerts for new vulnerabilities
        default: "monitor"
        enum: ["monitor", "test"]
    steps:
      - run:
          name: Run Snyk to check Docker image
          command: snyk << parameters.type >> --docker << parameters.image >>:<< parameters.tag >> --file=<< parameters.dockerfile >> --project-name=<< parameters.project >> << parameters.args >>

examples:
  install_snyk:
    description: Installing Snyk as a build step
    usage:
      version: 2.1
      orbs:
        snyk: garethr/snyk@x.y.z
      jobs:
        build:
          docker:
            - image: circleci/buildpack-deps:stretch
          steps:
            - snyk/install_snyk
  check_code_with_snyk:
    description: Checkout your source code and run snyk monitor
    usage:
      version: 2.1
      orbs:
        snyk: garethr/snyk@x.y.z
      jobs:
        build:
          docker:
            - image: circleci/buildpack-deps:stretch
          steps:
            - checkout
            - snyk/install_snyk
            - snyk/check_code_with_snyk
  check_docker_with_snyk:
    description: Run snyk monitor for a specific Docker image, useful when building the image at the same time
    usage:
      version: 2.1
      orbs:
        snyk: garethr/snyk@x.y.z
      jobs:
        build:
          docker:
            - image: circleci/buildpack-deps:stretch
          steps:
            - setup_remote_docker
            - snyk/install_snyk
            - snyk/check_docker_with_snyk:
                image: nginx
  check_docker_image_vulnerabilities:
    description: Run snyk monitor for a Docker image
    usage:
      version: 2.1
      orbs:
        snyk: garethr/snyk@x.y.z
      workflow:
        image_validation:
          jobs:
            - check_docker_image_vulnerabilities:
                image: nginx


jobs:
  check_docker_image_vulnerabilities:
    description: Check a Docker image for vulnerabilities as part of a workflow
    parameters:
      image:
        type: string
        description: The image repository to check
      tag:
        type: string
        description: The image tag to check
        default: latest
      args:
        type: string
        description: Pass arbitrary arguments to the Snyk CLI
        default: ""
      save:
        type: boolean
        description: Whether or not to save the results to Snyk for monitoring
        default: true
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - run:
          name: Pull image
          command: docker pull << parameters.image >>:<< parameters.tag >>
      - install_snyk
      - check_docker_with_snyk:
          image: << parameters.image >>
          tag: << parameters.tag >>
          args: << parameters.args >>
          dockerfile: ""
          type: test
      - when:
          condition: << parameters.save >>
          steps:
            - check_docker_with_snyk:
                image: << parameters.image >>
                tag: << parameters.tag >>
                args: << parameters.args >>
                project: << parameters.image >>:<< parameters.tag >>
                dockerfile: ""
